pipeline

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -15,21 +15,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
-    - name: change Directory
-      run: cd cli
+
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: '1.21.5'
-
-    - name: Build
-      run: cd cli && go build -o . -v ./...
-    - name: Upload Bin
-      uses: actions/upload-artifact@v4
-      with:
-        name: Go-Bin
-        path: cli/driving-journal-estimate
-        if-no-files-found: error
 
     - name: Test
       run: cd cli && go install github.com/jstemmer/go-junit-report/v2@latest && go test -v ./... -json 2>&1 | go-junit-report -parser gojson > testResults.xml
@@ -41,15 +31,15 @@ jobs:
         path: cli/testResults.xml
         if-no-files-found: error
 
-  report:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-    - uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      name: Upload Report
-      with:
-        artifact: /test-results-(.*)/           # artifact name
-        name: JEST Tests                  # Name of the check run which will be created
-        path: '*.xml'                     # Path to test results (inside artifact .zip)
-        reporter: jest-junit              # Format of test results
+#  report:
+#    runs-on: ubuntu-latest
+#    needs: build
+#    steps:
+#    - uses: dorny/test-reporter@v1
+#      if: success() || failure()    # run this step even if previous step failed
+#      name: Upload Report
+#      with:
+#        artifact: /test-results-(.*)/           # artifact name
+#        name: JEST Tests                  # Name of the check run which will be created
+#        path: '*.xml'                     # Path to test results (inside artifact .zip)
+#        reporter: jest-junit              # Format of test results
